### ISSUE TITLE
Trying the first example

### ISSUE THREAD

**Issue by LorenzoPanico** [MrNothing/AI-Blocks#13]
i get this error: (doing nothing but running the just cloned project)

 Traceback (most recent call last):
 File "C:\Users\lorenzo\AppData\Local\Temp/main.py", line 1524, in <module>
 instance_0.Run()
 File "C:\Users\lorenzo\AppData\Local\Temp/main.py", line 861, in Run
 _y = self._model.Run(self.X)
 File "C:\Users\lorenzo\AppData\Local\Temp/main.py", line 1046, in Run
 graph = self.model_elements[e].Run(graph, reuse=reuse)
 File "C:\Users\lorenzo\AppData\Local\Temp/main.py", line 1182, in Run
 if i<len(self.variables)/2-1 and self.use_relu:
 AttributeError: 'object_4' object has no attribute 'use_relu'

**Comment by LorenzoPanico** [comment]
treid running a second time and got this:
Traceback (most recent call last):
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 686, in _call_cpp_shape_fn_impl
 input_tensors_as_shapes, status)
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
 c_api.TF_GetCode(self.status.status))
 tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 784 and 1024 for 'MatMul' (op: 'MatMul') with input shapes: [?,784], [1024,256].
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
 File "C:\Users\lorenzo\AppData\Local\Temp/main.py", line 1524, in <module>
 instance_0.Run()
 File "C:\Users\lorenzo\AppData\Local\Temp/main.py", line 861, in Run
 _y = self._model.Run(self.X)
 File "C:\Users\lorenzo\AppData\Local\Temp/main.py", line 1046, in Run
 graph = self.model_elements[e].Run(graph, reuse=reuse)
 File "C:\Users\lorenzo\AppData\Local\Temp/main.py", line 1181, in Run
 h = tf.matmul(h, W) + b
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\math_ops.py", line 1891, in matmul
 a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\ops\gen_math_ops.py", line 2436, in _mat_mul
 name=name)
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
 op_def=op_def)
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2958, in create_op
 set_shapes_for_outputs(ret)
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2209, in set_shapes_for_outputs
 shapes = shape_func(op)
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\ops.py", line 2159, in call_with_requiring
 return call_cpp_shape_fn(op, require_shape_fn=True)
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 627, in call_cpp_shape_fn
 require_shape_fn)
 File "C:\Users\lorenzo\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\common_shapes.py", line 691, in _call_cpp_shape_fn_impl
 raise ValueError(err.message)
 ValueError: Dimensions must be equal, but are 784 and 1024 for 'MatMul' (op: 'MatMul') with input shapes: [?,784], [1024,256].

**Comment by MrNothing** [comment]
Hi, that example is quite old, just select the neuron object and replace 1024 with 784 in the scene.
I will replace the example project, sorry about that.

**Comment by LorenzoPanico** [comment]
yeah working now

**Comment by LorenzoPanico** [comment]
is that correct? https://ibb.co/d3X7HG

**Comment by MrNothing** [comment]
Yes this is the expected behavior, I am closing the ticket.
