### ISSUE TITLE
AI-Blocks cannot be opened because of a problem. (MacOS)

### ISSUE THREAD

**Issue by sukkamehu** [MrNothing/AI-Blocks#8]
Can't start newest version build for Mac, I'm on MacOS High Sierra.

Prompt:
> Check with the developer to make sure AI-Blocks works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.
> 
> Click Report to see more detailed information and send a report to Apple.

**Comment by MrNothing** [comment]
Try this version: https://github.com/MrNothing/AI-Blocks/releases/tag/v1.5-beta

**Comment by sukkamehu** [comment]
Still no luck, now it says "The application “AI-Blocks” can’t be opened."

but if I quickly debug

In info.plist there is wrong Mac OS version
"<string>macosx10.1010.10</string>"

In Whatsapp, also build by Electron in that same file there is
"<string>macosx10.1210.12</string>"

Mayb it could work if you would build it with newer version of Electron or could set that os version newer.

**Comment by MrNothing** [comment]
Thank you so much for the feedback. I will try with the latest version of electron. I will let you know when the next release is up.

**Comment by senseb** [comment]
+1 with the sample problem, please let me know when this case is closed. thank you. @MrNothing

**Comment by iou2much** [comment]
+1. look forward to new version. thanks a lot

**Comment by MrNothing** [comment]
The latest build was tested and validated on OSX10.12 (Sierra): https://github.com/MrNothing/AI-Blocks/releases/tag/v1.5.2-beta

I'm sorry for the delay, I had to setup an OSX virtual machine and install/re-build everything from there. Also check out the docs and tutorials: https://mrnothing.github.io/AI-Blocks/index.html

Closing the issue.

**Comment by iou2much** [comment]
<img width="1164" alt="default" src="https://user-images.githubusercontent.com/2812471/33355632-3e72dd92-d4f3-11e7-8acd-76a64f6a25bc.png">

  @MrNothing , Thank you for your great work.  I can open it now, but seems all blank, in OSX10.13.1( High Sierra ).

**Comment by sukkamehu** [comment]
I can confirm that it opens exactly like in picture @iou2much sent in High Sierra.

**Comment by MrNothing** [comment]
I'm reopening the issue then. 
Until I can investigate on a real OSX, I invite you to build the project directly from your computers. Install nodejs and pull the project and type `npm install`. To test the app type `npm run test`.

**Comment by iou2much** [comment]
okay. I pull the latest code, and it's running well with `npm run test`, but got error when I tried to pack it.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.9.1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'pack-mac' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prepack-mac', 'pack-mac', 'postpack-mac' ]
5 info lifecycle aiblocs@0.1.5~prepack-mac: aiblocs@0.1.5
6 info lifecycle aiblocs@0.1.5~pack-mac: aiblocs@0.1.5
7 verbose lifecycle aiblocs@0.1.5~pack-mac: unsafe-perm in lifecycle true
8 verbose lifecycle aiblocs@0.1.5~pack-mac: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/chibs/Documents/code/github/DL/AI-Blocks/Sources/node_modules/.bin:/usr/local/sbin:/usr/local/share/dotnet-dev-osx-x64.1.1.4:/Users/chibs/playground/AI/themes/speech-reg/kaldi-ctc/src/fstbin:/Users/chibs/playground/AI/themes/speech-reg/kaldi-ctc/src/featbin:/Users/chibs/bin:/usr/local/protobuf-3.1.0/bin:/usr/local/miniconda2/bin:/Applications/CMake.app/Contents/bin/:/usr/local/python3.5/bin/:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/:/usr/local/Cellar/scala/2.11.8//bin:/usr/local/Cellar/docker/1.12.0//bin:/bin:/Applications/SageMath:/Applications/SageMath/bin:/Users/chibs/playground/bigdata-stack/hbase/bin:/Users/chibs/playground/bigdata-stack/flume/bin:/Users/chibs/playground/bigdata-stack/hive/bin:/Users/chibs/playground/bigdata-stack/spark/bin:/Users/chibs/playground/bigdata-stack/hadoop/bin:/Users/chibs/playground/bigdata-stack/hadoop/sbin::/usr/bin:/Users/chibs/.sdkman/candidates/springboot/current/bin:/opt/oracle/instantclient:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/go/bin:/usr/local/apache-maven-3.3.3/bin:/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home//bin:/usr/local/mysql/bin:/usr/local/gradle-2.4/bin/:/Users/chibs/Library/Android/sdk/tools:/usr/local/lib:/usr/local/go/bin:/Users/chibs/Documents/code/github/hadoop-src/flume/bin:/usr/local/Cellar/hadoop/2.7.1/bin:/usr/local/Cellar/hadoop/2.7.1/sbin:/Users/chibs/playground/bigdata-stack/hive-2.0.0/bin:/Users/chibs/playground/bigdata-stack/spark/bin:/usr/local/apache-maven-3.3.3/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home//bin:/usr/local/mysql/bin:/usr/local/gradle-2.4/bin/:/Users/chibs/Library/Android/sdk/tools:/usr/local/lib:/usr/local/go/bin:/Users/chibs/playground/bigdata-stack/kylin/bin:/Users/chibs/playground/bigdata-stack/zeppelin/bin:/usr/local/Cellar/octave/4.0.3/bin:/usr/local/texlive/2016/bin/x86_64-darwin:/Users/chibs/playground/bigdata-stack/sbin:/Users/chibs/.local/bin
9 verbose lifecycle aiblocs@0.1.5~pack-mac: CWD: /Users/chibs/Documents/code/github/DL/AI-Blocks/Sources
10 silly lifecycle aiblocs@0.1.5~pack-mac: Args: [ '-c', 'electron-builder --mac dir' ]
11 silly lifecycle aiblocs@0.1.5~pack-mac: Returned: code: 1  signal: null
12 info lifecycle aiblocs@0.1.5~pack-mac: Failed to exec pack-mac script
13 verbose stack Error: aiblocs@0.1.5 pack-mac: `electron-builder --mac dir`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid aiblocs@0.1.5
15 verbose cwd /Users/chibs/Documents/code/github/DL/AI-Blocks/Sources
16 verbose Darwin 17.2.0
17 verbose argv "/usr/local/Cellar/node/8.9.1/bin/node" "/usr/local/bin/npm" "run" "pack-mac"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error aiblocs@0.1.5 pack-mac: `electron-builder --mac dir`
22 error Exit status 1
23 error Failed at the aiblocs@0.1.5 pack-mac script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by MrNothing** [comment]
Did you get the problem when building the project or when you run the mac build? The mac build is not working, you have to run the project from the sources in mac.
